### ISSUE TITLE
Correct spelling of company name ...

### ISSUE THREAD

**Issue by KarstenGorkow** [insite-gmbh/iDoc#13]
... is "insite GmbH". 
See iDoc|About.
A link to our home page would be nice (even if one can reach it via Kontaktformular)
www.insite-gmbh.de

**Comment by insite-Jan** [comment]
The logo in the top-right corner links to the website but I also was planning to add something like this to the getInvolved/about pages since they look so empty right now:  
![idoc_getinvolved_tiles](https://cloud.githubusercontent.com/assets/18348021/21885282/39f4aefa-d8b7-11e6-98f0-2017804206d4.png)
(replace something on the about page with the contact-us div for example)

**Comment by insite-Jan** [comment]
[I did a take on the tiles for the about page and updated the build of the site which can be seen here.](https://insite-gmbh.github.io/iDoc/about/insite.html)  
I would also add the tiles to the "Get Involved" page, with some small changes:
- the GitHub tile directly links to the repo instead of to the company on GitHub
- replace "Contact us" with something else

Any feedback/suggestions?

**Comment by proemmer** [comment]
The  H  in insite GmbH should be uppercase!

**Comment by proemmer** [comment]
The tiles are looking good, but if you scroll down the footer is before the tiles.

**Comment by proemmer** [comment]
I would prefer to open the link in the same tab, not in a new one. Because this breaks the flow.

**Comment by proemmer** [comment]
Could we use also tiles in the main page for   Projects, Get Involved, and About?  Or add some image to that page?
Because this page is really empty and the tiles are looking very cool.

**Comment by insite-Jan** [comment]
> The H  in insite GmbH should be uppercase!

Oops, fixed it for my next commit

> The tiles are looking good, but if you scroll down the footer is before the tiles.

This is a little bit tricky, because the tiles are in the .md file (adding them through templates would be complicated because we'd need conditional templates which only are added to specific docs). I made the position absolute, so they are not right below the text, but at the bottom instead (on normal screen-sizes, you should not be able to scroll on that page), but I can try to make it relative to the text somehow.

> I would prefer to open the link in the same tab, not in a new one. Because this breaks the flow.

All of the links or a specific one? What about the link with the logo in the top-right corner (I'd also change the background like in the navbar on-hover)?

> Could we use also tiles in the main page for Projects, Get Involved, and About? Or add some image to that page?

Yes, I'd suppose, once we are happy with the tiles on the about page, I'll copy them to other pages so I only need to change the content

**Comment by KarstenGorkow** [comment]
Please keep in mind: costs of beautification vs. benefits of beautification ... I've no problem with a better looking page, as long as the time needed to beautify it stays within certain limits ... keep in mind: so far only we and a few customers _may_ read and browse this stuff ...

**Comment by KarstenGorkow** [comment]
but: content should be clear and accurate, that's the main point imho.

**Comment by insite-Jan** [comment]
Yes, I think we then should just make sure, the tiles are not messing up the page in certain situations (like overlapping with important parts) and stay in a suitable place. As long, as the concept stays the same, I should be able to clone them to another page in a couple of minutes

**Comment by proemmer** [comment]
All of the links, because you have also the context menu to open it in a new tab.

**Comment by insite-Jan** [comment]
- i fixed the problems regarding the tiles colliding with stuff on screens <1920x1080, they should now scale appropriately with height/width as described [in my last commit](https://github.com/insite-gmbh/iDoc/commit/c943cfa0d3eb9deec9d9cb980d0a911973d52f35)
- i changed the links to open in the same tab
- typos should be fixed

I think, this can be closed. If you want me to add something similar to another page, I'd suggest we create a new issue for it
